// AUTO-GENERATED by scripts/fetch-spot-images.mjs — Wikipedia images per attraction.
export const SPOT_IMAGES: Record<string, string> = {
  "Chengdu Research Base of Giant Panda Breeding": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Chengdu_Research_Base_Eingang.jpg/800px-Chengdu_Research_Base_Eingang.jpg",
  "Ciqikou": "https://upload.wikimedia.org/wikipedia/commons/1/17/Ciqikou_Cross.jpg",
  "Forbidden City": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Forbidden_City_-_View_from_Coal_Hill.jpg/800px-The_Forbidden_City_-_View_from_Coal_Hill.jpg",
  "Hongya Cave": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg/800px-202308_Hongya_Cave_at_night_from_Qiansimen_Bridge.jpg",
  "Jinli": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Jingli.jpeg/800px-Jingli.jpeg",
  "Jiufen": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/A-mei_Tea_House.jpg/800px-A-mei_Tea_House.jpg",
  "Leshan Giant Buddha": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/36275-Leshan_%2849067653383%29.jpg/800px-36275-Leshan_%2849067653383%29.jpg",
  "Liziba station": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/%E6%9D%8E%E5%AD%90%E5%9D%9D%E7%AB%99%E8%BD%BB%E8%BD%A8%E7%A9%BF%E6%A5%BC_0023.png/800px-%E6%9D%8E%E5%AD%90%E5%9D%9D%E7%AB%99%E8%BD%BB%E8%BD%A8%E7%A9%BF%E6%A5%BC_0023.png",
  "Mutianyu": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Great_Wall_of_China_July_2006.JPG/800px-Great_Wall_of_China_July_2006.JPG",
  "National Palace Museum": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/NationalPalace_MuseumFrontView.jpg/960px-NationalPalace_MuseumFrontView.jpg",
  "Oriental Pearl Tower": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Oriental_Pearl_Tower_20251126.jpg/800px-Oriental_Pearl_Tower_20251126.jpg",
  "Ruins of St. Paul's": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/%E5%A4%A7%E4%B8%89%E5%B7%B4%E7%89%8C%E5%9D%8A.jpg/800px-%E5%A4%A7%E4%B8%89%E5%B7%B4%E7%89%8C%E5%9D%8A.jpg",
  "Shilin Night Market": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Shilin_night_market_alley_2.jpg/800px-Shilin_night_market_alley_2.jpg",
  "Star Ferry": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Star_Ferry%2C_Victoria_Harbour_%2831002395685%29.jpg/960px-Star_Ferry%2C_Victoria_Harbour_%2831002395685%29.jpg",
  "Summer Palace": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Longevity_Hill_of_the_Summer_Palace.jpg/800px-Longevity_Hill_of_the_Summer_Palace.jpg",
  "Taipei 101": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Taipei_Taiwan_Taipei-101-Tower-01.jpg/960px-Taipei_Taiwan_Taipei-101-Tower-01.jpg",
  "Temple of Heaven": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Temple_of_Heaven_20160323_01.jpg/800px-Temple_of_Heaven_20160323_01.jpg",
  "The Bund": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Bund_2.jpg/800px-The_Bund_2.jpg",
  "Tian Tan Buddha": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Tian_Tan_Buddha_2023081302.jpg/800px-Tian_Tan_Buddha_2023081302.jpg",
  "Tianmen Mountain": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tianmen_38330-Zhangjiajie_%2849047525877%29.jpg/800px-Tianmen_38330-Zhangjiajie_%2849047525877%29.jpg",
  "Victoria Peak": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/High_West_and_Victoria_Peak_from_Victoria_Gap_%28crop1%29.jpg/800px-High_West_and_Victoria_Peak_from_Victoria_Gap_%28crop1%29.jpg",
  "Wuhou Shrine": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Pavilion_-_Wuhou_Shrine_-_Chengdu%2C_China_-_DSC05444.jpg/960px-Pavilion_-_Wuhou_Shrine_-_Chengdu%2C_China_-_DSC05444.jpg",
  "Wulingyuan": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/1_tianzishan_wulingyuan_zhangjiajie_2012.jpg/800px-1_tianzishan_wulingyuan_zhangjiajie_2012.jpg",
  "Yangtze River Cableway": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Chongqing_Changjiang_Cableway.jpg/800px-Chongqing_Changjiang_Cableway.jpg",
  "Yu Garden": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Shanghai_-_Yu_Garden_-_0035.jpg/800px-Shanghai_-_Yu_Garden_-_0035.jpg",
  "Zhangjiajie Glass Bridge": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/ZhangjiajieGlassByHighestBridges.jpg/800px-ZhangjiajieGlassByHighestBridges.jpg",
  "Zhangjiajie National Forest Park": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/1_tianzishan_wulingyuan_zhangjiajie_2012.jpg/800px-1_tianzishan_wulingyuan_zhangjiajie_2012.jpg",
  "Zhujiajiao": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/1_zhujiajiao_2023_aerial.jpg/800px-1_zhujiajiao_2023_aerial.jpg",
};

export function spotImageFor(title: string): string | undefined {
  return SPOT_IMAGES[title];
}
